name: Wakatime workflow

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # At 00:00.
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master # this action name
        with:
          BLOCKS: -> # optional
          IGNORED_LANGUAGES: YAML JSON TOML, zsh, docker, # optional
          SECTION_NAME: waka # optional
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_EDITORS: true
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_OS: true
          SHOW_PROJECTS: false
          SHOW_TIME_ZONE: true
          WAKATIME_API_KEY: ${{ secrets.WAKA_TIME_API_KEY }}
